### ISSUE TITLE
Run CWL workflows in CCC

### ISSUE THREAD

**Issue by avirshup** [Autodesk/molecular-simulation-tools#1]
User story: 

Run CWL workflows via CCC (using the standalone CWL runner).

**Comment by avirshup** [comment]
- [ ] provide CWL using docker and MDT: @avirshup 
- [ ] Run the workflow with CWLTool in docker: @dionjwa

**Comment by dionjwa** [comment]
Finished: https://github.com/Autodesk/cloud-compute-cannon/pull/133
