### ISSUE TITLE
Travis built MST images and run tests in Travis-CI

### ISSUE THREAD

**Issue by dionjwa** [Autodesk/molecular-simulation-tools#166]
**Problem:**

Deployment takes a long time, due to jenkins needing to build the MST image.

Also Travis-CI can run tests on pull requests, ensuring that no compilation or build errors get into the deploy-ready branch.

**Solution:**

Have Travis-CI test and build the MST docker image. Then jenkins just needs to reference and deploy.

**Comment by dionjwa** [comment]
This *may* duplicate Autodesk/molecular-design-applications#159

**Comment by justinmc** [comment]
https://github.com/Autodesk/molecular-design-applications/pull/159 is blocked by the molviewer until we can use their code publicly.  Currently Travis is failing on `npm install` because the molviewer code isn't there.  I'm pretty sure that problem would be encountered here too.

**Comment by dionjwa** [comment]
https://github.com/Autodesk/molecular-simulation-tools/pull/267

**Comment by dionjwa** [comment]
Linked to this ticket is the subsequent Jenkins build fixes:
https://jira.autodesk.com/browse/BWP-255

**Comment by dionjwa** [comment]
Finished: 
https://travis-ci.org/Autodesk/molecular-simulation-tools

![image](https://zube.io/files/Autodesk/847e48a9c0f7639b479e13a028d6c14c.png)

**Comment by dionjwa** [comment]
![image](https://zube.io/files/Autodesk/864c681a933418bd529e25ced67bca04.png)
