### ISSUE TITLE
Combine "Email" and "Run"

### ISSUE THREAD

**Issue by justinmc** [Autodesk/molecular-simulation-tools#184]
Malte wants it to work like this: 
![pasted image at 2017_02_14 11_26 am](https://cloud.githubusercontent.com/assets/389558/23325459/493d2e86-faaa-11e6-94cb-43eaacfea902.png)

I believe this was mainly in response to users not understanding the flow through the steps and to the run button.

**Comment by avirshup** [comment]
@justinmc  I assume the new move towards login means that we don't need to worry about this? Please go ahead and close if so.

**Comment by justinmc** [comment]
@avirshup This actually was already merged!  I forgot to tag this issue in the PR.  https://github.com/Autodesk/molecular-simulation-tools/pull/229

I think this "run step" idea will merge with the "CCC/CWL steps" that we've been talking about for the future.
