### ISSUE TITLE
Structures don't appear in viewer in current master branch

### ISSUE THREAD

**Issue by avirshup** [Autodesk/molecular-simulation-tools#188]
This is for current master 5e8172e - both when I build locally and in our internal dev deployment

![image](https://cloud.githubusercontent.com/assets/9388007/23527116/79e07950-ff49-11e6-9e87-e609060e80b7.png)

However, it works fine on production, which is a5573ec8

**Comment by justinmc** [comment]
@avirshup It looks like @dionjwa and @PeterRJones are right, the `checkS3Url` endpoint failure is the problem.  I mocked the endpoint and returned a 200, and the structure showed up again.

The last time I changed the molviewer code was 26 days ago, could that be when this started?  Seems like that's too far back...  https://github.com/Autodesk/molecular-design-applications/commit/1cac1359c02b9d86fa20736633026e34c5ba8bd4

**Comment by justinmc** [comment]
It wasn't the molviewer code change, it was a change to our backend routes: https://github.com/Autodesk/molecular-design-applications/pull/179

Before that PR, we sent routes that looked like pages (don't have the api prefix) to index.html.  So `/checkS3Url` was receiving a 200 when it shouldn't have been, and that PR that changed our 404 routes made `/checkS3Url` get a 404 now!  We were totally lucky that the molviewer was working at all before.

This is the same problem that @dane1122 ran into when we tried to integrate the molviewer into her wasm project.
