### ISSUE TITLE
Review Wasm Code

### ISSUE THREAD

**Issue by justinmc** [Autodesk/molecular-simulation-tools#207]
Review @dane1122's wasm/javascript code.

**Comment by dane1122** [comment]
https://git.autodesk.com/t-leeday/lammps-browser
- my c++ code is inside the emscripten/ folder and is called lmps_web.cpp

**Comment by justinmc** [comment]
@dane1122 I'm just going to dump a bunch of commentary here, let me know if you have questions or anything.

  * Code architecture
    - I see you're using a couple of different javascript files and globals. I think that's fine for a small project like this, but if it starts to be confusing for you as the author, you can use modules to declare the imports/exports of a file.
  * Your use of the molviewer looks awesome.  I might ask you for help with the animation API later :)
  * Calling C++ methods via JS
    - Tell me if this is right: `lmps_web.cpp` is compiled to `emscripten.*`, which exports C++ stuff as the `Module` global in the browser?
      - I appear to be able to run this in the latest stable Chrome.  Shouldn't I need Canary?  Is this falling back to asm.js?
    - Is the part where you download `emscripten.wasm` and set it on `Module` part of the generated emscripten code?  Talking about this: https://git.autodesk.com/t-leeday/lammps-browser/blob/master/emscripten/lmps.html#L91
  * Blocking the UI
    - I noticed that clicking some of the buttons blocks the UI (the browser freezes for a bit).  I know that you and Dion were talking about using Web Workers, right?  That might be a good way to alleviate this problem.  Or maybe it doesn't matter at all for this demo :)
  * The "RUN MINIMIZATION" button doesn't work for me, gives a console error.

I think that's it, it's awesome that you've gotten all of this to work!  In the future if you want me to review changes you make, it might be worth it to open a pull request and have me review your changes there.  Maybe it doesn't matter for a 1 person project though, whatever you prefer.

**Comment by justinmc** [comment]
Regarding https://git.autodesk.com/t-leeday/molecule-simulation:

  * It's possible to break things in weird ways by entering crazy values into the inputs. It might not matter for the sake of this demo, but that could be smoothed out with some input validation.

**Comment by dane1122** [comment]
Hey Justin, thank you for looking into this for me!

* Code Architecture
   * Thank you so much! In the https://git.autodesk.com/t-leeday/molecule-simulation repository, I tried to the JS code into separate JS files!


* Calling C++ methods via JS
   * You have it right! `lmps_web.cpp` is compiled into `emscripten.*` which exports C++ stuff as the `Module` global. 
    * The compile command https://git.autodesk.com/t-leeday/lammps-browser/blob/master/emscripten/README.md allows us to fallback to `asm.js` if `wasm` isn't supported on the browser!
   * That part of the code was generated by emscripten when I used the compile command to output as `emscripten.html` instead of `emscripten.js`. I realized that it's required to run things in `wasm` so I just took that code snippet!

* Blocking the UI
   * I use *lammps-browser* to primarily develop c++ code. In the *molecule-simulation* repository, I ensure to run the lammps code as a separate webworker to prevent blocking of UI
   * I just fixed "RUN MINIMIZATION" and pushed it to master.. Should work now :)

**Comment by dane1122** [comment]
Regarding https://git.autodesk.com/t-leeday/molecule-simulation repository

* It's posible to break things by entering crazy values... Usually the *x*, *y*, *z* values should be within -10 to +10... I will definitely put in some input validation!

* I was thinking the same thing about the viewer! It looks a bit too wide right now. I will try to find the size that works well on the page.

Thank you Justin for taking the time to look into this! To make pull requests, do I need to add you as a contributor??

**Comment by justinmc** [comment]
@dane1122 About separate js files, if you use something like [webpack](https://webpack.github.io/), then instead of relying on globals, you can do things like this:

```
import { DEMO_PDB } from './demo.js';
```

It helps a lot with encapsulation.  I wouldn't worry about it unless the code starts to get unmanageable for you without it though.

For the input validation, there are some easy attributes you can add to them that might be all you need in this case (like `min` and `max`).  See [input on MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input).

And for pull requests, it looks like both of your repos are "public" on the private Autodesk github, so I think I should be able to access them fine.  Just tag me as a reviewer and I should get a notification.
