### ISSUE TITLE
Pulling dynamics

### ISSUE THREAD

**Issue by avirshup** [Autodesk/molecular-simulation-tools#213]
When this is done, users can:
  - select whether to _displace_ or _add a force_ to the atom selection (using a radio button)
  - enter the x,y, and z components of the force in text boxes

**Comment by dane1122** [comment]
@avirshup Aaron, I pushed "pull" to master. Could you look at it and see if it looks similar to what you would expect? 
To do the pull motion you have to,
1. check off the __add force__ radio box
2. Type in force amounts in x, y, z (i.e. x = 100 y = 0.0 z = 0.0)
3. Click on part of the molecule you want to apply the force
4. To stop applying the force, just click anywhere on the viewer (__NOT__ the molecule)

**Comment by dane1122** [comment]
in master
