### ISSUE TITLE
After minimization, animation appears to get stuck in a loop

### ISSUE THREAD

**Issue by avirshup** [Autodesk/molecular-simulation-tools#217]
After clicking on an atom to trigger a displacement and subsequent minimization, the animation seems to get stuck in a loop of 6 frames

![stuck_minimization.gif](https://zube.io/files/Autodesk/cfab95d528a796a284fcf2b4829d4d61.gif)

**Comment by dane1122** [comment]
I believe this is an issue related to simulation box size. I don't have a good solution for this issue yet.

**Comment by avirshup** [comment]
After playing with this a little more last night, I _think_ this is by situations when we do something really unrealistic to the atoms. For instance, moving one residue right on top of another one - in that case, the minimization seems to stuck.

The solution to this is probably #218 - we need a way to detect ridiculous states like this and, probably, rewind time until they are no longer ridiculous

**Comment by dane1122** [comment]
Rewinding is not possible since the c++ program just terminates... Maybe we can recreate lammps system when this happens??

**Comment by avirshup** [comment]
Really, it just quits? Sigh. Then yeah, if there's no exception to catch or anything, it would be great to just restart the LAMMPS from an earlier point in time.

**Comment by dane1122** [comment]
I added a way of notifying the user that the simulation crashed so they can reload it (this way, they are at least notified and can reload the molecule to restart the simulation instead of system just being unresponsive!)
