### ISSUE TITLE
Automatic recovery from simulation errors

### ISSUE THREAD

**Issue by avirshup** [Autodesk/molecular-simulation-tools#218]
When LAMMPS fails with an error, we should:
 1. restore the state of the molecule from the last simulation 
 2. run a fast minimization
 3. continue dynamics

**Comment by dane1122** [comment]
Can't recover since the wasm/asm.js module itself gets messed up on bad exit. Will try to reload molecule from the start when LAMMPS fails...

**Comment by dane1122** [comment]
commit 71ea3b2597be15d626092bbc8bba8d061135aaa4

Slightly more graceful: alert box notifies user to reload the molecule (i.e. press the top button)
Can't get the system to restart automatically without the user pressing the button due to issues related to `webworker`

**Comment by dane1122** [comment]
in dev
