### ISSUE TITLE
Decide Surface Volume Drawing API (Orbitals)

### ISSUE THREAD

**Issue by justinmc** [Autodesk/molecular-simulation-tools#236]
Look at the 3dmol api to see how it draws orbitals.  Come up with a way for MST to draw orbitals using @ktbolt's new molviewer surface drawing api that works for everyone.

**Comment by justinmc** [comment]
@ktbolt MDT uses 3dmol's [addIsoSurface](http://3dmol.csb.pitt.edu/doc/$3Dmol.GLShape.html#addIsosurface) method to draw orbitals.  Check out [MDT's code where we use it](https://github.com/Autodesk/molecule-3d-for-react/blob/master/src/components/molecule_3d.jsx#L90).  Our state consists of the `orbital` object, which has params `cube_file`, `iso_val`, and `opacity`.

What parameters are you thinking of for the molviewer's volume drawing api?  Would it be something we could easily convert these 3 parameters to on the frontend, or would it require some scientific computing in Python?

**Comment by ktbolt** [comment]
Here is the set of API calls that will draw an orbital:

    var api = window.AdskMolView;

    // Create volume object and return its ID.
    var volumeID = api.createVolumeFromData(volumeData, dataFormat);

    // Get volume data range.
    var range = api.getVolumeValuesRange(volumeID);
    var minValue = range.min;
    var maxValue = range.max;
    var isoLevel = (minValue + maxValue) / 2.0;

    // Create isosurface material.
    color = 0x770000;
    transparent = false;
    opacity = 0.2;
    var material = new THREE.MeshPhongMaterial({ color: color, opacity: opacity, transparent: transparent});
    material.side = THREE.DoubleSide;

    // Extract an isosurface.
    var mesh = api.extractVolumeIsosurface(volumeID, isoLevel, material);
    api.drawMesh(mesh);


Note that 'volumeData' has type '"arraybuffer'.

**Comment by justinmc** [comment]
Great, that looks to me like something we could use without doing any extra conversion of the normal MDT data.  @avirshup will you be able to return MDT-style `orbitals` data from a workflow so that we can use this API as is?

**Comment by ktbolt** [comment]
The createVolumeFromData() function supports two formats: ADSK and MRC. The ADSK format is something I defined as something we could convert other formats for electron density data to. I write it out using Python like this:

    fp = open(file_name, 'wb')

    # 16 byte header.
    headerText = "ADSK"
    header = array('B', '{0: <16}'.format(headerText))
    header.tofile(fp)

    # Number of cells (voxels) in ijk.
    dims = array('i', [inum, jnum, knum] )
    dims.tofile(fp)

    # Volume extent in Cartesian space. 
    extent = array('f', [xmin, ymin, zmin, xmax, ymax, zmax] )
    extent.tofile(fp)

    # The cell widths.
    cell_dims = array('f', [dx, dy, dz])
    cell_dims.tofile(fp)

    # Data.
    data = array('f', values)
    data.tofile(fp)

**Comment by avirshup** [comment]
Yes, this will be no problem to generate with MDT. However, we probably will want to generate it on demand - each of these files will be ~2 MB, and there are potentially hundreds that could be generated from a single QM calculation.

Unless I can find a javascript library to do it (unlikely) the frontend will need to call another endpoint to _generate_ these files before they can be passed to the viewer API. I can definitely set up a docker container to do this via CCC, that may be the easiest for now

**Comment by avirshup** [comment]
@ktbolt - the actual function that needs to be evaluated for the MO grid is this:

![image](https://cloud.githubusercontent.com/assets/9388007/24222732/4e2d4c6c-0f10-11e7-9271-341ec0d5291f.png)

Nothing to complicated there, really. All of those numbers with subscripts would be passed in as inputs. How slow would javascript be evaluating this on a 100x100x100 grid?

**Comment by ktbolt** [comment]
How large is the basis? About 1000?

**Comment by avirshup** [comment]
Yeah, that's a large but not unrealistic number

**Comment by avirshup** [comment]
@ktbolt - for your adsk-format code above, that's a binary file, right? Are things like endian-ness potentially a portability problem?

**Comment by avirshup** [comment]
Quick and dirty MDT code to write an ADSK-format volume file (not sure if data array is being written in the right order)

```python
import moldesign as mdt
from moldesign import units as u

def orb_to_grid(mol, orbital=None, npts=100):
    from moldesign.helpers import VolumetricGrid
    if orbital is None:
        orbital = mol.wfn.orbitals.canonical[mol.homo]
    positions = mol.positions
    grid = VolumetricGrid(positions,
                          padding=4.0*u.angstrom,
                          npoints=npts)
    coords = grid.xyzlist().reshape(3, grid.npoints**3).T
    values = orbital(coords)
    grid.fxyz = values.reshape(npts, npts, npts)
    return grid
    
def grid_to_file(fname, grid):
    from numpy import array
    
    with open(fname, 'wb') as fp:
        # 16 byte header.
        headerText = "ADSK"
        header = array(['{0: <16}'.format(headerText)])
        header.tofile(fp)

        # Number of cells (voxels) in ijk.
        dims = array([grid.npoints, grid.npoints, grid.npoints], dtype='i')
        dims.tofile(fp)

        # Volume extent in Cartesian space. 
        xmin, xmax = u.array(grid.xr).value_in(u.angstrom)
        ymin, ymax = u.array(grid.yr).value_in(u.angstrom)
        zmin, zmax = u.array(grid.zr).value_in(u.angstrom)
        extent = array([xmin, ymin, zmin, xmax, ymax, zmax], dtype='f')
        extent.tofile(fp)

        # The cell widths.
        cell_dims = array([grid.dx, grid.dy, grid.dz], dtype='f')
        cell_dims.tofile(fp)

        # Data.
        array(grid.fxyz.T, dtype='f').tofile(fp)

mol = mdt.from_smiles('c1ccccc1')
mol.set_energy_model(mdt.models.RHF, basis='sto-3g')
mol.calculate()

fp = grid_to_file('myfile.dat', orb_to_grid(mol))
```

**Comment by avirshup** [comment]
Loaded it with
```
var pluscolor = 0x770000;
var minuscolor = 0x000077;
var transparent = true;
var opacity = 0.4;
var material_plus = new THREE.MeshPhongMaterial({ color: pluscolor, opacity: opacity, transparent: transparent});
var material_minus = new THREE.MeshPhongMaterial({ color: minuscolor, opacity: opacity, transparent: transparent});
material_plus.side = THREE.DoubleSide;
material_minus.side = THREE.DoubleSide;

var api = AdskMolView;

var oReq = new XMLHttpRequest();
oReq.open("GET", "https://localhost:4321/myfile.dat", true);
oReq.responseType = "arraybuffer";

oReq.onload = function (oEvent) {
  var arrayBuffer = oReq.response;
  var volumeId = AdskMolView.createVolumeFromData(arrayBuffer, 'ADSK');
  var mesh = api.extractVolumeIsosurface(volumeId, 0.01, material_plus);
  api.drawMesh(mesh);
  var mesh = api.extractVolumeIsosurface(volumeId, -0.01, material_minus);
  api.drawMesh(mesh);
}

oReq.send(null);
```
![image](https://cloud.githubusercontent.com/assets/9388007/24282409/84b278c2-101c-11e7-8e72-c5810c2163fc.png)

**Comment by ktbolt** [comment]
I don't think endianness is an issue because you are creating the file.

**Comment by ktbolt** [comment]
The data array is assumed to have i (x-direction) varying the fastest, then j and then k.

**Comment by justinmc** [comment]
Looks really great 😍
