### ISSUE TITLE
Drag/Pull atoms with your mouse

### ISSUE THREAD

**Issue by avirshup** [Autodesk/molecular-simulation-tools#255]
This requires [Autodesk/molecular-simulation-tools#254](https://zube.io/autodesk/molecular-design-applications/c/420) 

When that's done, this issue is for:
 - being able to _drag_ an atom by clicking and dragging with your mouse.
 - being able to _pull_ an atom (exerting a force that pulls the atom toward your mouse, with a total amount of force that scales with the distance between the mouse and the atom)

**Comment by dane1122** [comment]
https://git.autodesk.com/t-leeday/molecule-simulation/pull/13

- pull atoms with molecule! 
@ktbolt @avirshup
