### ISSUE TITLE
Interactive MD demo deployment plan

### ISSUE THREAD

**Issue by avirshup** [Autodesk/molecular-simulation-tools#256]
This will be to deploy Day's app as a static webpage demo that lets users run one (or a few) preloaded molecule (like it works now).

This is _separate_ from the interactive simulation MST app. The purpose here is specifically to show our leadership on Wasm and share it with the community, especially MD developers. The point here is just to give a demo of numerical simulation in the browser using WebAssembly.

@dane1122 , please work with @florencio-mazzoldi to figure out where we should post this (if it makes sense, github pages would seem to be a good option). Let's also make sure that we're using the MV in a kosher way.

**Comment by dane1122** [comment]
http://molecularsimulation.dev.bionano.autodesk.com/interactive-sim/
