### ISSUE TITLE
Interactive simulation / Wasm documentation

### ISSUE THREAD

**Issue by avirshup** [Autodesk/molecular-simulation-tools#257]
This is a writeup of @dane1122 's awesome work on browserifying LAMMPS.

Specifically, I'd like to see: 
 - a step-by-step description of how to compile LAMMPS into webassembly (with links to the scripts/makefiles/packages that you used)
 - a presentation of the benchmarking results of browser vs. CPU
 - A description of (and links to) the interactive simulation demo page
 - A technical description of how the page is architected and deployed (especially things like how the simulation webworker and the molviewer talk to each other)

**Comment by dane1122** [comment]
Specifically, I'd like to see:

* a step-by-step description of how to compile LAMMPS into webassembly (with links to the scripts/makefiles/packages that you used)
 https://github.com/dane1122/lammps/tree/emscripten (forked from LAMMPS repo. Maybe make a pull request?)
 https://git.autodesk.com/t-leeday/lammps-browser/tree/master/emscripten
 
* a presentation of the benchmarking results of browser vs. CPU
* A description of (and links to) the interactive simulation demo page
 https://git.autodesk.com/t-leeday/molecule-simulation
* A technical description of how the page is architected and deployed (especially things like how the simulation webworker and the molviewer talk to each other)
