### ISSUE TITLE
Display ribbons view for all steps except results animation

### ISSUE THREAD

**Issue by avirshup** [Autodesk/molecular-simulation-tools#259]
It would be great to have this for prod on Thursday if possible. I'd like to see the default view (ribbons for the protein, sticks for the small molecules) everywhere except the final animation, where all sticks is OK for now.

**Comment by justinmc** [comment]
I'll prioritize this and shoot for Thursday!

**Comment by justinmc** [comment]
As of https://github.com/Autodesk/molecular-simulation-tools/issues/263, this will show "ribbon" before you press Run and "stick" afterwards.  I think this card requires the view to change when you click a given widget though, so it's not done yet.

**Comment by justinmc** [comment]
https://github.com/Autodesk/molecular-simulation-tools/pull/265 will do what I think is the full solution to this card:

![ribbon_slash_stick](https://cloud.githubusercontent.com/assets/389558/24682601/58e6a5c4-194f-11e7-8ca3-407e7ff8057e.gif)

**Comment by justinmc** [comment]
Closing since https://github.com/Autodesk/molecular-simulation-tools/pull/265 has been merged.
