### ISSUE TITLE
MST frontend dynamically creates apps from JSON specs

### ISSUE THREAD

**Issue by justinmc** [Autodesk/molecular-simulation-tools#283]
Zube: https://zube.io/autodesk/genome-designer/c/1852

This represents our "parent" high level goal for the MVP push for MST.  The app should generically generate an "app" from json, run its computes generically based on definitions in the json, and be deployable to production.

Initial work was done in this open PR and it will be used directly or indirectly as a feature branch for this: https://github.com/Autodesk/molecular-simulation-tools/pull/280

**Comment by justinmc** [comment]
The above issues are my initial idea of what it will take to get to MVP.

**Comment by avirshup** [comment]
@justinmc  - will start posting questions here as I think of them. For now:

 - Are the [JSON](https://github.com/Autodesk/molecular-simulation-tools/blob/master/apps-data/apps/vde.js#L14) app specifications ready to be consumed once the frontend is up?

**Comment by justinmc** [comment]
@avirshup The app json is already being consumed by the frontend and used to generate our apps in master right now.  The problem is that it's much simpler than our final specification is.  Anything not included in that linked json is still hardcoded.

[In my WIP PR](https://github.com/Autodesk/molecular-simulation-tools/pull/280/files#diff-32a976e73eb98c0c7891b084b2d66a5fR28) I've already started adding complexity to the widget data.  The main thing that's still missing for MVP is the ability to specify arbitrary docker images and commands for a widget to run, and for multiple RUN widgets to be supported.

The way that you would create a new app in json is to add it to the folder containing all the other apps and then include it in the [main app js file](https://github.com/Autodesk/molecular-simulation-tools/blob/master/apps-data/main.js).

Let me know if that doesn't answer your question!

**Comment by avirshup** [comment]
Yeah, that makes total sense. So the plan is to keep updating the app definitions in `apps-data/apps/` as each of these linked issues gets completed?

**Comment by justinmc** [comment]
Yeah that's right.  That app json is used as an npm module and could also easily be in a separate repo if needed.

**Comment by justinmc** [comment]
This is finished off and in master as of Closing with https://github.com/Autodesk/molecular-simulation-tools/pull/299!
