### ISSUE TITLE
MVP: Generic Execution Calls

### ISSUE THREAD

**Issue by justinmc** [Autodesk/molecular-simulation-tools#285]
#### Part of the MVP push: https://github.com/Autodesk/molecular-simulation-tools/issues/283

Currently we're still using calls like "exectuteApp0Step0" etc. to do RUN and LOAD backend work.  This needs to be made generic.

First, in the widget data in the app json, we'll need to add a few fields to contain a docker image and command ([example location for VDE app](https://github.com/Autodesk/molecular-simulation-tools/blob/master/apps-data/apps/vde.js#L14)).  Then we'll need to connect with the backend and run the indicated docker workflow.  I believe the endpoint already exists.  Also, it should be possible to look up the docker image/command on the server, or to pass it from the client, so a decision needs to be made on which to do.

**Comment by avirshup** [comment]
This seems reasonable to me - will it be generic enough to support both the CWL endpoint and the single-job CCC endpoint?

**Comment by justinmc** [comment]
I believe @dionjwa has a separate endpoint for both, is that right?  Do we have a way to distinguish the two in the json Dion?

**Comment by dionjwa** [comment]
Yes, it can do both. The CWL endpoint is there, but as-yet not very well tested, since I wasn't sure how far along the need for it was.

**Comment by justinmc** [comment]
Closing with https://github.com/Autodesk/molecular-simulation-tools/pull/299
