### ISSUE TITLE
Benchmark WebAssembly / LAMMPS performance

### ISSUE THREAD

**Issue by avirshup** [Autodesk/molecular-simulation-tools#79]
Create a short report showing how LAMMPS performs on a CPU-based vs. a browser-based platform.

We'll want to compare:
 - several diffrent types of simulations (@avirshup will provide these from their prepackaged examples)
 - peak memory usage (if possible)
 - the effects of compiler optimization
 - scaling with system size (@avirshup will try to find an easy way to do this)

We'll also want to look at whether WASM gives the same answers as the CPU, although this will probably need to be done qualitatively because the simulations aren't deterministic

**Comment by justinmc** [comment]
I would totally be interested in this as a blog post if you guys are interested in writing it :)
